# Xiaomi Kernel Feature
obj-$(CONFIG_MILLET)	+= millet_core.o
obj-$(CONFIG_MILLET)	+= millet_pkg.o
obj-$(CONFIG_MILLET)	+= millet_hs.o
obj-$(CONFIG_XIAOMI_METIS)	+= metis.o
obj-$(CONFIG_SOFTWARE_OS3)	+= moon_func_os3.o
